# Generated by Django 3.2.6 on 2021-09-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default='_'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.TextField(default='_'),
        ),
    ]
