# Generated by Django 3.2.6 on 2021-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('fb', models.CharField(default='-', max_length=250)),
                ('tw', models.CharField(default='-', max_length=250)),
                ('yt', models.CharField(default='-', max_length=250)),
                ('ph', models.CharField(default='-', max_length=250)),
            ],
        ),
    ]
