# Generated by Django 3.2.6 on 2021-09-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picname',
            field=models.TextField(default='_'),
        ),
        migrations.AddField(
            model_name='article',
            name='picurl',
            field=models.TextField(default='_'),
        ),
    ]
